// Generated by https://quicktype.io

export interface ReportResume {
  date: Date;
  actNumber: string;
  plate: string;
  speed: number;
  location: string;
  maxSpeed: number;
  model: string;
  sensorId: string;
}
